# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snipetss', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('timecreated',)},
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='drivername',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.AddField(
            model_name='snippet',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
