# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipetss', '0004_auto_20180214_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='image/%d/'),
        ),
    ]
